version: '3.8'

services:
  supabase:
    image: supabase-community/supabase:latest
    restart: always
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.supabase.rule=Host(`${SUPABASE_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.supabase.entrypoints=websecure
      - traefik.http.routers.supabase.tls=true
      - traefik.http.routers.supabase.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.supabase-headers.headers.SSLRedirect=true
      - traefik.http.middlewares.supabase-headers.headers.STSSeconds=315360000
      - traefik.http.middlewares.supabase-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.supabase-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.supabase-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.supabase-headers.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.supabase-headers.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.supabase-headers.headers.STSPreload=true
      - traefik.http.routers.supabase.middlewares=supabase-headers@docker
    environment:
      - SUPABASE_POSTGRES_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_AUTH_ADMIN_EMAIL=${SUPABASE_ADMIN_EMAIL}
      - SUPABASE_AUTH_ADMIN_PASSWORD=${SUPABASE_ADMIN_PASSWORD}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - supabase_/var/lib/postgresql/data

volumes:
  supabase_

networks:
  proxy:
    external: true